=== allmaps/allmaps/packages/iiif-parser/schemas/image.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://allmaps.org/iiif-parser/schemas/image.json",
  "title": "Parsed IIIF Image Resource",
  "type": "object",
  "properties": {
    "uri": {
      "description": "Image Resource URI",
      "type": "string"
    },
    "type": {
      "type": "string",
      "const": "image"
    },
    "version": {
      "type": "integer",
      "enum": [
        2,
        3
      ]
    },
    "width": {
      "type": "integer",
      "description": "Width of image"
    },
    "height": {
      "type": "integer",
      "description": "Height of image"
    },
    "maxWidth": {
      "type": "integer"
    },
    "maxHeight": {
      "type": "integer"
    },
    "maxArea": {
      "type": "integer"
    },
    "quality": {
      "type": "string",
      "enum": [
        "native",
        "default"
      ]
    },
    "format": {
      "type": "string",
      "const": "jpg"
    },
    "fullImageUrl": {
      "type": "string"
    },
    "sizes": {
      "type": "array"
    },
    "tiles": {
      "type": "array"
    },
    "supportsAnyRegionAndSize": {
      "type": "boolean"
    },
    "canvasUri": {
      "type": "string"
    },
    "label": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "object"
        }
      ]
    },
    "sourceData": {
      "type": "object"
    }
  },
  "additionalProperties": false,
  "required": [
    "uri",
    "type",
    "version",
    "width",
    "height",
    "quality",
    "format",
    "fullImageUrl",
    "supportsAnyRegionAndSize"
  ]
}

=== allmaps/allmaps/packages/iiif-parser/test/parsed/nls-10146-101465411.image.2.parsed.json
{
  "uri": "https://mapview.nls.uk/iiif/10146/101465411",
  "type": "image",
  "version": 2,
  "width": 8932,
  "height": 6493,
  "quality": "default",
  "format": "jpg",
  "fullImageUrl": "https://mapview.nls.uk/iiif/10146/101465411/full/full/0/default.jpg",
  "tiles": [
    {
      "width": 256,
      "height": 256,
      "scaleFactors": [
        1,
        2,
        4,
        8,
        16,
        32,
        64
      ]
    }
  ],
  "supportsAnyRegionAndSize": true
}
