=== allmaps/allmaps/packages/annotation/schemas/map.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://allmaps.org/annotation/schemas/map.json",
  "title": "Georeferenced map",
  "type": "object",
  "properties": {
    "id": {
      "type": ["integer", "string"]
    },
    "gcps": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/gcp"
      }
    },
    "version": {
      "type": "integer",
      "enum": [1],
      "default": 1,
      "errorMessage": "Only version 1 is supported. Map should have property `version` with value `1`."
    },
    "image": {
      "$ref": "#/$defs/image"
    },
    "pixelMask": {
      "type": "array",
      "minItems": 3,
      "items": {
        "type": "array",
        "items": {
          "type": "integer"
        },
        "minItems": 2,
        "maxItems": 2
      },
      "errorMessage": "Invalid pixel mask. The property `pixelMask` must be an array of at least 3 points (`[x, y]`)."
    }
  },
  "required": ["image"],
  "$defs": {
    "gcp": {
      "type": "object",
      "properties": {
        "id": {
          "type": ["integer", "string"]
        },
        "image": {
          "$ref": "#/$defs/point"
        },
        "world": {
          "$ref": "#/$defs/point"
        }
      },
      "required": ["image", "world"],
      "errorMessage": "Invalid GCPs. Each GCP must have property `image` (`[x, y]`) and property `world` (`[lon, lat]`)."
    },
    "point": {
      "type": "array",
      "minItems": 2,
      "maxItems": 2,
      "items": {
        "type": "number"
      }
    },
    "image": {
      "type": "object",
      "properties": {
        "id": {
          "type": ["integer", "string"]
        },
        "uri": {
          "type": "string",
          "format": "uri",
          "errorMessage": "Invalid or missing image URI. Image property `uri` must be a [valid URI](https://datatracker.ietf.org/doc/html/rfc3986)."
        },
        "width": {
          "type": "integer",
          "errorMessage": "Invalid or missing image width. Image property `width` must be a valid integer."
        },
        "height": {
          "type": "integer",
          "errorMessage": "Invalid or missing image height. Image property `height` must be a valid integer."
        },
        "version": {
          "type": "integer",
          "enum": [2, 3],
          "default": 2,
          "errorMessage": "Invalid image version, only IIIF Image API 2.0 and 3.0 are supported. Image property `version` must be either `2` or `3`."
        }
      },
      "required": ["uri", "width", "height"],
      "errorMessage": "Invalid image. Image must be an object with required properties `uri`, `width` and `height`."
    }
  },
  "errorMessage": "Invalid map. A map must be an object with required property `image`."
}

=== allmaps/allmaps/apps/cli/test/26e384d4efabdb32.json
{
  "gcps": [
    {
      "world": [97.1805877419104, 3.2578402429992224],
      "image": [578, 3779]
    },
    {
      "world": [95.75768658834603, 2.8399231303739043],
      "image": [349, 3855]
    },
    {
      "world": [98.6704303085887, 3.5887634152449692],
      "image": [834, 3724]
    },
    {
      "world": [96.13028951090241, 4.147110928854772],
      "image": [396, 3629]
    },
    {
      "world": [98.78380465867059, 1.7403690250373955],
      "image": [845, 4039]
    },
    {
      "world": [95.30603649176652, 5.780419948549238],
      "image": [252, 3345]
    },
    {
      "world": [97.48314719079927, 5.244320402045915],
      "image": [625, 3441]
    }
  ],
  "image": {
    "id": "d144156fc3c7f96c",
    "uri": "https://cdm21033.contentdm.oclc.org/digital/iiif/krt/1022",
    "type": "ImageService2",
    "width": 3493,
    "height": 4292
  },
  "version": 1,
  "pixelMask": [
    [196, 3324],
    [861, 3323],
    [856, 4061],
    [369, 4057],
    [370, 3925],
    [305, 3852],
    [191, 3851]
  ]
}

=== allmaps/allmaps/packages/transform/test/input/map.pixelMask-single-point.json
{
  "id": "638c301276143e9a",
  "gcps": [
    {
      "world": [-71.0098934, 42.3384275],
      "image": [9944, 5819]
    },
    {
      "world": [-71.0298213, 42.3646445],
      "image": [4360, 253]
    },
    {
      "world": [-71.0399214, 42.3533058],
      "image": [3293, 3757]
    }
  ],
  "image": {
    "id": "2caaf62b5fe68a89",
    "uri": "https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:pv63jj022",
    "type": "ImageService2",
    "width": 10844,
    "height": 9131
  },
  "version": 1,
  "pixelMask": [[143, 44]]
}
